extend = "ruff-base.toml"

extend-exclude = [
  "**/*.ipynb",
  "obs*.py",
  "go.py",
  "go[0-9].py",
  "junk/",
]

# Some additional rules that are useful
lint.extend-select = [
"D205",  # One blank line required between summary line and description
]